# 节点配置
server:
  # 节点的外部访问IP地址
  addr: 127.0.0.1
  # 节点的TCP端口（用于Raft集群内部调度）
  tcp-port: 7999
  # 节点的HTTP端口（用于对外数据交互）
  http-port: 8000
# 要加入的节点
join:
  # 节点的外部访问IP地址
  addr:
  # 节点的HTTP端口（用于对外数据交互）
  http-port:
# 存储配置
store:
  # 数据存储目录
  path: ./data